### ISSUE TITLE
Package a paxctld.conf so users don't have to

### ISSUE THREAD

**Issue by ahhchuu** [coldhakca/coldkernel#11]

**Comment by Phoul** [comment]
Creating a paxd configuration will prevent users from needing to learn which pax flags are required for common applications to run. This should make coldkernel much more "plug-n-play".

**Comment by Phoul** [comment]
This is being worked on at https://github.com/coldhakca/coldkernel/tree/13_paxctld_debian

**Comment by Phoul** [comment]
We now package a paxctld.conf
