### ISSUE TITLE
fakeroot make-kpkg "deprecated"

### ISSUE THREAD

**Issue by 0x20c24** [coldhakca/coldkernel#24]
As Corsac pointed out[1][2] make-kpkg is not the preferred way to compile a kernel anymore, but using "make deb-pkg" instead of that.
I guess you can use "make rpm-pkg" on Centos to build the RPM package.

[1]: http://perso.corsac.net/~corsac/debian/kernel-grsec/PEREZ_Yves-Alexis_hardened-kernels.pdf slide 20 and 21
[2]: https://www.corsac.net/?post=1573

Cheers,
Peter

**Comment by Phoul** [comment]
This has been implemented in master with https://github.com/coldhakca/coldkernel/commit/444917f2bde32f483a22e8270e8360af6218975f. A new release will be tagged within the next few days.
