### ISSUE TITLE
similar project - grsecurity-installer - cooperation

### ISSUE THREAD

**Issue by adrelanos** [coldhakca/coldkernel#27]
There is a similar project. We have similar goals, funding and bounties.

- https://github.com/Whonix/grsecurity-installer
- which is a fork of https://github.com/rickard2/grsecurity-Debian-Installer that will hopefully be merged upstream when done
- our TODO and bounty: https://www.bountysource.com/issues/14471558-make-grsecurity-kernel-grsecurity-installer-work-inside-whonix

Interested to cooperate?

**Comment by Phoul** [comment]
Hi Adrelanos,

It sounds like there is potential for collaboration here, and we/I would be happy to discuss. Please send an email to contact<AT>coldhak<DOT>ca with details of what you're looking for.

Thanks!

**Comment by adrelanos** [comment]
Do we need to do this by mail or can this stay in public here?

**Comment by Phoul** [comment]
Email would be preferred. Coldhak is a team of 4 people, who do not all religiously check Github.
