### ISSUE TITLE
Do build testing of RPM builds

### ISSUE THREAD

**Issue by Phoul** [coldhakca/coldkernel#31]
Currently, we build test every coldkernel/grsecurity patch combination before release. This testing currently only happens for Debian-based platforms (Ubuntu, Debian, Debian Sid). 

We should expand coverage to all supported platforms.

**Comment by Phoul** [comment]
We have a server this can be done on, just needs configuring.

**Comment by marmarek** [comment]
Have you considered using Travis-CI? We use it at @QubesOS exactly for this. This will work only if the build will finish withing allowed max time (50min). We haven't managed that for Linux kernel, but this may be specific to our build script (we prepare chroot with Fedora there first...), or out configuration for the kernel (close to `make allmodconfig`).

**Comment by Phoul** [comment]
We now have a Fedora Jenkins slave, closing.
