### ISSUE TITLE
Debian instructions required update-grub

### ISSUE THREAD

**Issue by adrelanos** [coldhakca/coldkernel#36]
Without manually running `sudo update-grub` after installing coldkernel on Debian, coldkernel did not show up in grub boot menu.

I guess running update-grub is usually up to the kernel's postinst script in Debian or some dpkg trigger?

(Was using Qubes (#35), but this is probably not relevant here.)

**Comment by Phoul** [comment]
This step is not required in standard Debian (Or CentOS). This has been tested in Jessie, Stretch and Sid.
