### ISSUE TITLE
Document disk space requirements

### ISSUE THREAD

**Issue by Phoul** [coldhakca/coldkernel#37]
As pointed out in #32, we should document the disk space requirements for building coldkernel. 

After dependencies, 5GB is a safe amount of space. We do not currently have calculations including dependency sizes from a fresh install of CentOS / Debian / Ubuntu. This would be useful information to include in the README.

**Comment by tbaschak** [comment]
README.me includes "You will need (at least) 4GB of free disk space before starting the build." as of e7f6da96
