### ISSUE TITLE
Failure to insert module autofs4

### ISSUE THREAD

**Issue by PacketSmuggler** [coldhakca/coldkernel#42]
I have two identical VPS running CentOS-7-x86_64-Minimal-1511.iso installed under Xen hypervisor.

Each got an identical install of coldkernel as the first substantial thing done to them.

Each got an install of cPanel/WHM. First unit got configured, second just got the install.

First unit doesn't boot now, hanging with a Failed to insert module 'autofs4'.

I can't collect /run/initramfs/rdsosreport.txt as I'm nowhere near the system, but I did screen shot the last page if the details would help.

I'm going to try to duplicate this with the second system, seems like a long shot, can't imagine cPanel doing anything that would mess with a file system module, but I guess we'll see.

**Comment by Phoul** [comment]
Any update on this?

**Comment by Phoul** [comment]
Closing until confirmation.
