### ISSUE TITLE
Qubes: "Failed to open /proc: Permission denied"

### ISSUE THREAD

**Issue by micahflee** [coldhakca/coldkernel#49]
Every time I use `qvm-copy-to-vm` or `qvm-move-to-vm` to copy files into a VM based on my `debian-8-coldkernel` template, it displays this error message:

```
Failed to open /proc: Permission denied
```

However, the file actually does get copied, so it doesn't seem to be that much of a problem.

**Comment by Phoul** [comment]
coldkernel enables restrictions on /proc, which is causing this warning. 

This sounds more like an issue with qvm-* than an issue with coldkernel, if the file is successfully copying but still complaining. It likely wants but does not require something that is restricted from /proc. 

You can add users to guid 9001 (as mentioned at the bottom of the README) to disable the proc restrictions for that user.

**Comment by adrelanos** [comment]
Do you think this is a qvm-* issue? @marmarek

**Comment by marmarek** [comment]
It's used to link the file created by `open(..., O_TMPFILE)`. See `open(2)`. It's used to make the file [inaccessible](https://github.com/QubesOS/qubes-linux-utils/blob/master/qrexec-lib/unpack.c#L115-L125) until [fully copied](https://github.com/QubesOS/qubes-linux-utils/blob/master/qrexec-lib/unpack.c#L144-L149). Lack of this feature in some corner cases may lead to [security problem](https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-014-2015.txt). But operation will indeed continue. It was meant to not break file copy on older kernels (lacking O_TMPFILE support, <= 3.11), but I think now it can be strictly required.

So, I guess the solution should indeed be adding `user` user to group 9001.

**Comment by Phoul** [comment]
Interesting!

I will go ahead and get this information added to the README / add a
disclaimer to the blog post this evening.

Adding the user to group 9001 is the safest option in this case, as the
alternative is disabling proc restrictions entirely for all users.

Thanks!

**Comment by micahflee** [comment]
I've confirmed adding `user` to group 9001 removes the error message.
