### ISSUE TITLE
Qubes TemplateVM stops at login

### ISSUE THREAD

**Issue by hyperfekt** [coldhakca/coldkernel#56]
On starting up a patched TemplateVM, it stays in the starting-up state forever, and applications started from dom0 will not appear. Examining the logs shows that it requires a log in:
```
...
[.[32m  OK  .[0m] Started Qubes misc post-boot actions.
[.[32m  OK  .[0m] Reached target Multi-User System.
         Starting Update UTMP about System Runlevel Changes...
[.[32m  OK  .[0m] Started Update UTMP about System Runlevel Changes.
[    2.990432] grsec: denied priority change of process (rtkit-daemon:783) by /usr/lib/rtkit/rtkit-daemon[rtkit-daemon:783] uid/euid:113/113 gid/egid:123/123, parent /lib/systemd/systemd[systemd:1] uid/euid:0/0 gid/egid:0/0
 
 
Debian GNU/Linux 8 debian-8-coldkernel hvc0
 
debian-8-coldkernel login:
```

The instructions for a Qubes TemplateVM should probably be adapted to skip this, since it becomes unusable after the shutdown (one can still enter the VM console by using `sudo xl console [vmname]`).

PS: This is not an April Fool. ^^

**Comment by LimitedTime** [comment]
The same here: tried several times in the Qubes-supplied Debian 8 template, and also when upgraded to Debian 9.
This issue happens with the kernels newer than 4.8.17.
The 4.8.17 version builds, installs and works seemingly OK.
Every time it happens, there is a preceding error message during the kernel installation process. Specifically, during "sudo make install-deb", while  "setting" of the image operation.
The two "Issue #52" lines added to the coldkernel.config file before building, although it doesn't affect the outcome of this issue.

On a side note, the "Fix sources.list" portion in the kernel build instructions should be corrected:
The 
     deb http://httpredir.debian.org/debian jessie main contrib non-free
     deb-src http://httpredir.debian.org/debian jessie main contrib non-free
doesn't fetch right and could be replaced with:
     deb http://deb.debian.org/debian stretch main contrib non-free
     deb-src http://http.debian.net/debian stretch main contrib non-free

**Comment by LimitedTime** [comment]
P.S. Sorry I typed "stretch" in the suggested repositories above. Meant "jessie". :-)

**Comment by rtiangha** [comment]
A workaround is in https://github.com/coldhakca/coldkernel/issues/55 but an updated qubes-vm-kernel-support package with an updated u2mfn.c file for kernels 4.9 and higher has *finally* been pushed out and you'll need to install it on every template VM that you'll want to run the coldkernel on. Right now, it can be found in the current-testing repository so you'll need to temporarily enable it in order to access it. Otherwise, it should be pushed into the stable repository in a week or so (I hope, anyways).

**Comment by hyperfekt** [comment]
I can confirm this works, although the package is named `qubes-kernel-vm-support`. Thanks ^-^
