### ISSUE TITLE
Missing paxctl files

### ISSUE THREAD

**Issue by MikaelThalen** [coldhakca/coldkernel#9]
After installing dependencies, several of the paxctl files in Debian 8 are not available in /usr/sbin/

sudo paxctl -Cm /usr/sbin/grub-probe (available)
sudo paxctl -Cm /usr/sbin/grub-mkdevicemap (available)
sudo paxctl -Cm /usr/sbin/grub-setup (missing)
sudo paxctl -Cm /usr/bin/grub-script-check (missing)
sudo paxctl -Cm /usr/bin/grub-mount (missing)

Other available files are as follows:
grub-bios-setup
grub-install
grub-macbless
grub-mkconfig
grub-reboot
grub-set-default

**Comment by Phoul** [comment]
https://github.com/coldhakca/coldkernel/commit/d4e5e471e43a0d9106f1a0482bc91cfcaf2b7cc0 resolves this issue.

Thanks!
